baseURL: "https://yanasbakery.com"
languageCode: 'en-us'
title: "Yana's Bakery"
enableInlineShortcodes: true

# Disable built-in sitemap generator as it does not support link customization
disableKinds:
  - sitemap

# Enhanced taxonomies
taxonomies:
  category: categories
  dietary: dietary        # taxonomy for dietary terms
#  allergen: allergens     # taxonomy for allergen tracking
  confection: confections # taxonomy for product confection
  option: options         # taxonomy for product variants/flavors

permalinks:
  categories: "/categories/:slug/"
  confections: "/confections/:slug/"
  robots: "/robots.txt"

build:
  writeStats: false

# Media management
imaging:
  quality: 85
  resampleFilter: Lanczos
  anchor: Smart

# Asset pipeline
module:
  mounts:
    - source: assets
      target: assets
    - source: static
      target: static
    - source: content
      target: content

params:
  debug: true
  description: Handcrafted Memorable Bites
  email: yanas.cosbakery@gmail.com
  phone: '+17193018351'
  facebook: 'https://www.facebook.com/profile.php?id=61557290430496'
  instagram: 'https://www.instagram.com/yanas_cosbakery/'
  mainSections:
    - categories

#  categories:
#    cakes:
#      title: "Cakes"
#      description: "Cakes"
#      subcategories:
#        cookies:
#          title: "Sub cookies"
#    desserts:
#      title: "Desserts"
#      description: "Desserts"
#
#  # Allergen information
#  allergens:
#    gluten:
#      title: "Contains Gluten"
#      warning: "This product contains gluten"
#    dairy:
#      title: "Contains Dairy"
#      warning: "This product contains dairy"
#    nuts:
#      title: "Contains Nuts"
#      warning: "This product contains nuts"

  # Custom image resizing logic (keeping your existing configuration)
  images:
    products:
      listing:
        small:
          width: 300
          height: 250
        medium:
          width: 400
          height: 250
        large:
          width: 800
          height: 250
          lossless: false
          near_lossless: 60
          compression: 6
        2xsmall:
          width: 600,
          height: 500,
        2xmedium:
          width: 800,
          height: 518,
        2xlarge:
          width: 1600,
          height: 500,
      options:
        default_format: "webp"
        default_quality: 85
        fallback_format: "jpg"
        webp:
          compression: 6
          near_lossless: 60
          smart_subsample: true
          sharp_yuv: true

menu:
  main:
    - identifier: home
      name: Home
      url: /
      params:
        icon: home.svg
      weight: 1
    - identifier: cakes
      name: Cakes
      url: /confections/cakes/
      weight: 2
      params:
        icon: cake.svg
    - identifier: cookies
      name: Cookies
      url: /confections/cookies/
      weight: 2
      params:
        icon: cookie.svg
    - identifier: desserts
      name: Desserts
      url: /confections/desserts/
      weight: 2
      params:
        icon: dessert.svg
    - identifier: dietary
      name: Dietary Options
      weight: 5
      url: /dietary
      params:
        icon: dietary.svg
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
