baseURL: "https://yanasbakery.com/"
title: "Yana's Bakery"
enableInlineShortcodes: true

# Disable built-in sitemap generator as it does not support link customization
disableKinds:
  - sitemap

#languageCode: 'en-us'
#defaultContentLanguage: en
defaultContentLanguageInSubdir: false

#
#  https://gohugo.io/content-management/multilingual/#menus
#
languages:
  en:
    languageCode: "en"
    contentDir: "content/en"
    languageName: "English"
    weight: 0
    default: true
    params:
      market: "us"
      flag: "🇺🇸"
      currency: "$"
      unit: "lb"
    menus:
      main:
        - identifier: home
          name: Home
          url: /
          params:
            icon: home.svg
          weight: 1
        - identifier: cakes
          name: Cakes
          url: /confections/cakes
          weight: 2
          params:
            icon: cake.svg
        - identifier: cookies
          name: Cookies
          url: /confections/cookies
          weight: 2
          params:
            icon: cookie.svg
        - identifier: desserts
          name: Desserts
          url: /confections/desserts
          weight: 2
          params:
            icon: dessert.svg
#        - identifier: dietary
#          name: Dietary Options
#          weight: 5
#          url: /en/dietary
#          params:
#            icon: dietary.svg

  uk:
    languageCode: "uk"
    contentDir: "content/uk"
    languageName: "Українська"
    weight: 1
    params:
      flag: "🇺🇦"
      currency: "₴"
      unit: "кг"
    menus:
      main:
        - identifier: home
          name: Головна
          url: /uk
          params:
            icon: home.svg
          weight: 1
        - identifier: cakes
          name: Торти
          url: /uk/confections/cakes
          weight: 2
          params:
            icon: cake.svg
        - identifier: cookies
          name: Печиво
          url: /uk/confections/cookies
          weight: 3
          params:
            icon: cookie.svg
        - identifier: desserts
          name: Десерти
          url: /uk/confections/desserts
          weight: 4
          params:
            icon: dessert.svg
        - identifier: dietary
          name: Дієтичні опції
          weight: 5
          url: /uk/dietary
          params:
            icon: dietary.svg

# Remove any trailing slashes from internal URLs
#removePathAccents: true
cleanDestinationDir: true

# Enhanced taxonomies
taxonomies:
  category: categories
  dietary: dietaries        # taxonomy for dietary terms
#  allergen: allergens     # taxonomy for allergen tracking
  confection: confections # taxonomy for product confection
  option: options         # taxonomy for product variants/flavors

permalinks:
  categories: "/categories/:slug/"
  confections: "/confections/:slug/"
  robots: "/robots.txt"

build:
  writeStats: false

# Media management
imaging:
  quality: 85
  resampleFilter: Lanczos
  anchor: Smart

## Asset pipeline
mounts:
  - source: assets
    target: assets
  - source: static
    target: static
  - source: content
    target: content
params:
  debug: false
  description: Handcrafted Memorable Bites
  email: yanas.cosbakery@gmail.com
  phone: '+17193018351'
  facebook: 'https://www.facebook.com/profile.php?id=61557290430496'
  instagram: 'https://www.instagram.com/yanas_cosbakery/'
  mainSections:
    - categories

#  categories:
#    cakes:
#      title: "Cakes"
#      description: "Cakes"
#      subcategories:
#        cookies:
#          title: "Sub cookies"
#    desserts:
#      title: "Desserts"
#      description: "Desserts"
#
#  # Allergen information
#  allergens:
#    gluten:
#      title: "Contains Gluten"
#      warning: "This product contains gluten"
#    dairy:
#      title: "Contains Dairy"
#      warning: "This product contains dairy"
#    nuts:
#      title: "Contains Nuts"
#      warning: "This product contains nuts"

  # Custom image resizing logic (keeping your existing configuration)
  images:
    products:
      listing:
        small:
          width: 300
          height: 250
        medium:
          width: 400
          height: 250
        large:
          width: 800
          height: 250
          lossless: false
          near_lossless: 60
          compression: 6
        2xsmall:
          width: 600,
          height: 500,
        2xmedium:
          width: 800,
          height: 518,
        2xlarge:
          width: 1600,
          height: 500,
      options:
        default_format: "webp"
        default_quality: 85
        fallback_format: "jpg"
        webp:
          compression: 6
          near_lossless: 60
          smart_subsample: true
          sharp_yuv: true
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
